// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5KjLrzHFRtyzkMliRfH-_oGs2dMR149o',
    appId: '1:768826918238:web:a86c46af00d432385d7bcf',
    messagingSenderId: '768826918238',
    projectId: 'aircast-c39df',
    authDomain: 'aircast-c39df.firebaseapp.com',
    storageBucket: 'aircast-c39df.firebasestorage.app',
    measurementId: 'G-YJGYQ7EP8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-5HoqQjxENqe5EbAwZWs4x43qIMt_X7A',
    appId: '1:768826918238:android:8e165e8e7dbb9cc15d7bcf',
    messagingSenderId: '768826918238',
    projectId: 'aircast-c39df',
    storageBucket: 'aircast-c39df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBppQKoh0wQE5-6ePbpej-Xshpl5ak197s',
    appId: '1:768826918238:ios:df58762fadbdd6365d7bcf',
    messagingSenderId: '768826918238',
    projectId: 'aircast-c39df',
    storageBucket: 'aircast-c39df.firebasestorage.app',
    iosBundleId: 'com.example.aircast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBppQKoh0wQE5-6ePbpej-Xshpl5ak197s',
    appId: '1:768826918238:ios:df58762fadbdd6365d7bcf',
    messagingSenderId: '768826918238',
    projectId: 'aircast-c39df',
    storageBucket: 'aircast-c39df.firebasestorage.app',
    iosBundleId: 'com.example.aircast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5KjLrzHFRtyzkMliRfH-_oGs2dMR149o',
    appId: '1:768826918238:web:e579628cf41afaf95d7bcf',
    messagingSenderId: '768826918238',
    projectId: 'aircast-c39df',
    authDomain: 'aircast-c39df.firebaseapp.com',
    storageBucket: 'aircast-c39df.firebasestorage.app',
    measurementId: 'G-RCBGEBHGY7',
  );
}